image: starefossen/ruby-node

variables:
  JEKYLL_ENV: development
  LC_ALL: C.UTF-8
  BUNDLE_BUILD__NOKOGIRI: --use-system-libraries

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby

stages:
  - test
  - build
  - deploy

before_script:
  - bundle install --path vendor

pages:
  stage: test
  script:
  - bundle exec jekyll build -d public --config _config.yml,_config.dev.yml
  artifacts:
    paths:
    - public
  only:
  - master

build:
  stage: build
  variables:
    JEKYLL_ENV: production
  when: manual
  allow_failure: false
  script:
  - bundle exec jekyll build -d deploy
  dependencies: []
  artifacts:
    paths:
    - deploy
  only:
  - master

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  image: alpine:latest
  cache: {}
  when: on_success
  environment:
    name: 'NearlyFreeSpeech'
    url: https://augustodaniele.com.ar
  before_script:
  - 'which ssh-agent || ( apk update && apk add openssh-client bash rsync )'
  - eval $(ssh-agent -s)
  - echo "$PRODUCTION_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H $PRODUCTION_SERVER >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - rsync -hrvz --delete-before --exclude=.well-known -e ssh deploy/ "${SSH_USER_HOST_LOCATION}"
  dependencies:
  - build
  only:
  - master
