# Entorno
timezone: America/Argentina/Buenos_Aires
exclude: [README.md,rakefile.rb]

# Gems:
# - jekyll-sitemap
# - jekyll-feed

# Links
permalink: '/:categories/:title.html'

# Configuración básica
title: 'Porfolio de Augusto Daniele'
tagline: 'Porfolio web y cv.'
description: 'Porfolio personal y currículum vítae de Augusto Daniele.'
# url: 'http://tasken.github.io'
baseurl: ''

# Info básica
author:
  name: 'Augusto Daniele'
  url: 'http://augustodaniele.com.ar'

# NearlyFreeSpeech
destination: /home/public
keep_files: [demo]
url: 'http://augustodaniele.com.ar'

editor: 'nano'
git:
  branch: 'nf'
transfer:
  command: 'rsync'
  settings: '-av'
  source: '_site/''
  destination: '/home/public'
