# Entorno
timezone: America/Argentina/Buenos_Aires

# GitHub Pages:
# gems:
#   - jekyll-sitemap
#   - jekyll-feed

# Links
permalink: '/:categories/:title/'

# Configuración básica
title: 'Porfolio de Augusto Daniele'
tagline: 'Porfolio web y cv.'
description: 'Porfolio personal y currículum vítae de Augusto Daniele.'
baseurl: ''

# Info básica
author:
  name: 'Augusto Daniele'
  url: 'http://augustodaniele.com.ar'

# NearlyFreeSpeech
url: 'http://augustodaniele.com.ar'
destination: /home/public
keep_files: [demo,heuristica]
exclude: [README.md]
