# Entorno
timezone: America/Argentina/Buenos_Aires

# Links
permalink: '/:categories/:title/'

# Configuración básica
title: 'Porfolio de Augusto Daniele'
tagline: 'Porfolio web y cv.'
description: 'Porfolio personal y currículum vítae de Augusto Daniele.'

# Info básica
author:
    name: 'Augusto Daniele'
    url: 'https://augustodaniele.com.ar'

# NearlyFreeSpeech
url: 'https://augustodaniele.com.ar'
exclude: ['vendor', 'Gemfile*', 'rakefile.rb']

plugins:
    - jekyll-tidy
    - jekyll-sitemap

collections:
    proyectos:
        output: true
        permalink: /:collection/:path/
