# Entorno
timezone: America/Argentina/Buenos_Aires

# GitHub Pages:
# gems:
#   - jekyll-sitemap
#   - jekyll-feed

# Links
permalink: '/:categories/:title/'

# Configuración básica
title: 'Porfolio de Augusto Daniele'
tagline: 'Porfolio web y cv.'
description: 'Porfolio personal y currículum vítae de Augusto Daniele.'
baseurl: ''

# Info básica
author:
  name: 'Augusto Daniele'
  url: 'https://augustodaniele.com.ar'

# NearlyFreeSpeech
url: 'https://augustodaniele.com.ar'
destination: /home/public
keep_files: ['demo', '.well-known']
exclude: [README.md]
