# Entorno
timezone: America/Argentina/Buenos_Aires

# GitHub Pages:
# gems:
#   - jekyll-sitemap
#   - jekyll-feed
# url: 'https://tasken.github.io'

# Links
permalink: '/:categories/:title.html'

# Configuración básica
title: 'Porfolio de Augusto Daniele'
tagline: 'Porfolio web y cv.'
description: 'Porfolio personal y currículum vítae de Augusto Daniele.'
baseurl: ''

# Info básica
author:
  name: 'Augusto Daniele'
  url: 'http://augustodaniele.com.ar'

# NearlyFreeSpeech
destination: /home/public
keep_files: [demo]
exclude: [README.md]
url: 'http://augustodaniele.com.ar'
