source 'https://rubygems.org'

gem 'autoprefixer-rails'
gem 'image_optim'
gem 'image_optim_pack'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-sitemap'
gem 'jekyll-tidy'
gem 'rake'
gem 'therubyracer'
gem 'uglifier'
